apiVersion: v1
kind: Pod
metadata:
  name: diagnostic-pod # уникальное имя пода
  namespace: dev
spec:
  serviceAccountName: diagnostic-sa  # cервисный аккаунт для пода (должен совпадать с именем sa d service-account.yaml)
  containers:
  - name: diagnostic
    image: bitnami/kubectl:latest                     # контейнер с утилитой kubectl
    command: ["sh", "-c", "kubectl get pods -n dev"]  # команда, выполняемая в контейнере
