apiVersion: v1
kind: Service
metadata:
  name: mysql-service # должно совпадать с serviceName в StatefulSet
  namespace: dev
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: mysql
