apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service # должно совпадать с serviceName в StatefulSet и name в Service mysql
#        - name: WORDPRESS_DB_PASSWORD
#          value: root
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wp_user
        - name: WORDPRESS_DB_PASSWORD
          value: wp_passwd
        ports:
        - containerPort: 80

        volumeMounts:
          - name: wordpress-data
            mountPath: /var/www/html

      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc
