---
- name: Install Apache server
  package:
    name: "{{ apache_package }}"
    state: present

- name: Start and enable Apache service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Install PHP and required extensions
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ php_packages }}"

- name: Deploy WordPress
  block:
    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extract WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Set permissions for WordPress
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: apache
        group: apache
        mode: "0755"
