global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - reddit-ui:9292/
        - reddit-ui:9292/new
        - reddit-post:5000
        - reddit-comment:9292
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'reddit'
    static_configs:
      - targets: ['reddit-ui:9292', 'reddit-post:5000', 'reddit-comment:9292']
