apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Values.namespace }}
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
  MYSQL_PASSWORD: {{ .Values.mysql.password }}
