apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
  namespace: {{ .Values.namespace }}
spec:
  serviceName: mysql-service
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        envFrom:
        - secretRef:
            name: mysql-secrets
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mysql.storage }}
