apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-m02

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage # указываем имя StorageClass, который создавали ранее
  local:
    path: /mnt/data/m02 # как понял, это путь на самой ноде, куда будет сохранять (но сильно не уверен)

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - minikube-m02

# в nodeAffinity выбираем ноду, на которой будет pv находиться (методом сопоставления по имени ноды)
