apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        envFrom:
        - configMapRef:
            name: wordpress-config
        - secretRef:
            name: mysql-secrets
        resources:
          requests:
            cpu: {{ .Values.wordpress.resources.requests.cpu }}
            memory: {{ .Values.wordpress.resources.requests.memory }}
          limits:
            cpu: {{ .Values.wordpress.resources.limits.cpu }}
            memory: {{ .Values.wordpress.resources.limits.memory }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-pvc
